export const cards = [
  {
    imgSrc: 'cat.jpg',
    imgAlt: 'cat',
    title: 'My sweet cat',
    author: 'Alice Braun',
    tags: ['cat', 'animals', 'pets', 'cute'],
    likes: 152,
    views: 169,
  },
  {
    imgSrc: 'car.jpg',
    imgAlt: 'car',
    title: 'Do you like speed?',
    author: 'Jon111',
    tags: ['speed', 'cars'],
    likes: 120,
    views: 134,
  },
  {
    imgSrc: 'people.jpg',
    imgAlt: 'people on the street',
    title: 'Why do we always hurry?',
    author: 'Molly',
    tags: ['job', 'life', 'people'],
    likes: 257,
    views: 311,
  },
  {
    imgSrc: 'bird.jpg',
    imgAlt: 'bird',
    title: 'God never makes errors',
    author: 'Paul',
    tags: ['life', 'bird', 'parrot', 'happy'],
    likes: 325,
    views: 478,
  },
  {
    imgSrc: 'friends.jpg',
    imgAlt: 'friends',
    title: 'All we need is love',
    author: 'girl111',
    tags: ['love', 'friends', 'life', 'smile', 'swing'],
    likes: 311,
    views: 407,
  },
  {
    imgSrc: 'girls.jpg',
    imgAlt: 'girls',
    title: 'Better a new friend than an old foe',
    author: 'ly_ly',
    tags: ['friends', 'friend', 'girls'],
    likes: 684,
    views: 704,
  },
  {
    imgSrc: 'horses.jpg',
    imgAlt: 'horses',
    title: 'Freedom and peace',
    author: 'Kate25',
    tags: ['freedom', 'speed', 'life'],
    likes: 157,
    views: 209,
  },
  {
    imgSrc: 'love.jpg',
    imgAlt: 'love',
    title: 'Endless love',
    author: 'SARA',
    tags: ['love', 'lions', 'animals', 'wild'],
    likes: 562,
    views: 597,
  },
  {
    imgSrc: 'mountains-1.jpg',
    imgAlt: 'mountains',
    title: 'Never stop dreaming',
    author: 'Jane_K',
    tags: ['mountains', 'earth', 'land', 'beautiful'],
    likes: 457,
    views: 500,
  },
  {
    imgSrc: 'mountains-2.jpg',
    imgAlt: 'mountains',
    title: 'The future belongs to those, who believe in beauty of their dreams',
    author: 'Vikkii',
    tags: ['future', 'life'],
    likes: 647,
    views: 741,
  },
  {
    imgSrc: 'people-with-beer.jpg',
    imgAlt: 'people',
    title:
      'Every day can not be good, but there is something good in every day',
    author: 'lola',
    tags: ['life', 'friends', 'goodday'],
    likes: 126,
    views: 207,
  },
  {
    imgSrc: 'sea.jpg',
    imgAlt: 'sea',
    title: 'Be happy… not because everything is good but because you can ...',
    author: 'alice',
    tags: ['sea', 'vacation'],
    likes: 643,
    views: 678,
  },
  {
    imgSrc: 'sloth.jpg',
    imgAlt: 'sloth',
    title: 'Never regret anything that made you smile',
    author: '_nobody_',
    tags: ['smile', 'laugh', 'life'],
    likes: 574,
    views: 921,
  },
  {
    imgSrc: 'swimmer.jpg',
    imgAlt: 'swimmer',
    title:
      'All we have to decide is what to do with the time that is given to us',
    author: 'EmilY',
    tags: ['girl', 'yellow', 'water'],
    likes: 479,
    views: 512,
  },
  {
    imgSrc: 'zebra.jpg',
    imgAlt: 'zebra',
    title: 'Those who cannot change their minds cannot change anything',
    author: 'wilDPerson',
    tags: ['big_thoughts'],
    likes: 258,
    views: 367,
  },
];
